### ISSUE TITLE
Mistake of the argument ?

### ISSUE THREAD

**Issue by oamatsu** [Azure-Samples/media-services-v3-node-tutorials#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
modify index.js

47 const inputFile = "test.mp4";
48 const inputUrl = null;

$ node index.js

### Any log messages given by the failure
>
creating encoding transform...
getting job input from arguments...
accountName: undefined
Error: accountName cannot be null or undefined and it must be of type string.
    at Assets._createOrUpdate (/home/ec2-user/sites/media-services-v3-node-tutorials/AMSv3Samples/StreamFilesWithDRMSample/node_modules/azure-arm-mediaservices/lib/operations/assets.js:412:13)
    at /home/ec2-user/sites/media-services-v3-node-tutorials/AMSv3Samples/StreamFilesWithDRMSample/node_modules/azure-arm-mediaservices/lib/operations/assets.js:1832:14
    at new Promise (<anonymous>)
    at Assets.createOrUpdate (/home/ec2-user/sites/media-services-v3-node-tutorials/AMSv3Samples/StreamFilesWithDRMSample/node_modules/azure-arm-mediaservices/lib/operations/assets.js:1831:14)
    at createInputAsset (/home/ec2-user/sites/media-services-v3-node-tutorials/AMSv3Samples/StreamFilesWithDRMSample/index.js:234:53)
    at getJobInputFromArguments (/home/ec2-user/sites/media-services-v3-node-tutorials/AMSv3Samples/StreamFilesWithDRMSample/index.js:216:11)
    at /home/ec2-user/sites/media-services-v3-node-tutorials/AMSv3Samples/StreamFilesWithDRMSample/index.js:91:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

### Expected/desired behavior
>run success.

### OS and Version?
> Amazon Linux 2 AMI (HVM), SSD Volume Type - ami-0ce107ae7af2e92b5

### Versions
>

### Mention any other details that might be useful

 NG -> 88     let input = await getJobInputFromArguments(uniqueness);
 OK -> 88     let input = await getJobInputFromArguments(resourceGroup, accountName, uniqueness);

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johndeu** [comment]
Updating this sample in the new branch for the latest SDK. CLosing this for now, as I have changed the way this code works in the DRM sample now.
